---
- hosts: all
  become: true
  vars:
    - pri_domain_name: 'vagrant.local'
  roles:
    - role: ansible-apache2
    - role: ansible-mariadb-mysql
    - role: ansible-ntp
    - role: ansible-snmpd
    - role: ansible-timezone
    - role: ansible-cacti
  tasks:
