---
- src: https://github.com/mrlesmithjr/ansible-apache2.git
- src: https://github.com/mrlesmithjr/ansible-cacti.git
- src: https://github.com/mrlesmithjr/ansible-lighttpd.git
- src: https://github.com/mrlesmithjr/ansible-mariadb-mysql.git
- src: https://github.com/mrlesmithjr/ansible-nginx.git
- src: https://github.com/mrlesmithjr/ansible-ntp.git
- src: https://github.com/mrlesmithjr/ansible-snmpd.git
- src: https://github.com/mrlesmithjr/ansible-timezone.git
