---
- name: redhat | installing pre-reqs
  yum:
    name: "{{ item }}"
    state: present
  notify:
    - restart httpd
  with_items: cacti_redhat_packages
  when: >
        ansible_distribution != "Fedora"

- name: redhat | installing pre-reqs
  dnf:
    name: "{{ item }}"
    state: present
  notify:
    - restart httpd
  with_items: cacti_redhat_packages
  when: >
        ansible_distribution == "Fedora"
